% Initialize matrix A and B 
A = [1, 2, 4; 5, 3, 2]
B = [1, 3, 4; 1, 1, 1]

% Initialize constant s 
s = 2

% See how element-wise addition works
add_AB = A + B 

% See how element-wise subtraction works
sub_AB = A - B

% See how scalar multiplication works
mult_As = A * s

% Divide A by s
div_As = A / s

% What happens if we have a Matrix + scalar?
add_As = A + s


In [4]:
import numpy as np

Initialize matrix A and B 

In [12]:
A = np.matrix('1 2 4; 5 3 2')
B = np.matrix('1 3 4; 1 1 1')

print (A)
print ('\n')
print (B)

[[1 2 4]
 [5 3 2]]


[[1 3 4]
 [1 1 1]]


Initialize constant s 

In [17]:
s = 2

See how element-wise addition works

In [14]:
add_AB = A + B
print(add_AB)

[[2 5 8]
 [6 4 3]]


See how element-wise subtraction works

In [15]:
sub_AB = A - B
print(sub_AB)

[[ 0 -1  0]
 [ 4  2  1]]


See how scalar multiplication works

In [18]:
mult_As = A * s
print(mult_As)

[[ 2  4  8]
 [10  6  4]]


Divide A by s

In [19]:
div_As = A / s
print(div_As)

[[0.5 1.  2. ]
 [2.5 1.5 1. ]]


What happens if we have a Matrix + scalar?

In [20]:
add_As = A + s
print(add_As)

[[3 4 6]
 [7 5 4]]
