# Learn how to use basic numpy library to do linear algebra calculations

In [9]:
import numpy as np

Initialize a 3*3 Matrix

In [15]:
A = np.matrix('1 2 3; 4 5 6; 7 8 9; 10 11 12')

Initialize a vector 

In [16]:
V = np.array([1,2,3])

Get the dimension of the matrix A and vector V

In [17]:
dim_A = A.shape
dim_V = V.shape

let's index into the 2nd row 3rd column of matrix A
(Note: Python is 0-based indexing)

In [18]:
A_23 = A.item((1,2))

In [19]:
print (A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
print(V)

[1 2 3]


In [21]:
print (dim_A)

(4, 3)


In [22]:
print (dim_V)

(3,)


In [23]:
print (A_23)

6
