% Initialize random matrices A and B 
A = [1,2;4,5]
B = [1,1;0,2]

% Initialize a 2 by 2 identity matrix
I = eye(2)

% The above notation is the same as I = [1,0;0,1]

% What happens when we multiply I*A ? 
IA = I*A 

% How about A*I ? 
AI = A*I 

% Compute A*B 
AB = A*B 

% Is it equal to B*A? 
BA = B*A 

% Note that IA = AI but AB != BA

In [3]:
import numpy as np

In [4]:
A = np.matrix("1 2;4 5")
B = np.matrix("1 1;0 2")
I = np.identity(2)

print (I)

[[1. 0.]
 [0. 1.]]


In [6]:
IA = I * A
AI = A * I
AB = A * B
BA = B * A

In [7]:
print (IA)
print (AI)

[[1. 2.]
 [4. 5.]]
[[1. 2.]
 [4. 5.]]


In [8]:
print (AB)
print (BA)

[[ 1  5]
 [ 4 14]]
[[ 5  7]
 [ 8 10]]


% Initialize matrix A 
A = [1,2,0;0,5,6;7,0,9]

% Transpose A 
A_trans = A' 

% Take the inverse of A 
A_inv = inv(A)

% What is A^(-1)*A? 
A_invA = inv(A)*A

In [10]:
A = np.matrix("1 2 0;0 5 6;7 0 9")
A_trans = np.transpose(A)

print (A)
print(A_trans)

[[1 2 0]
 [0 5 6]
 [7 0 9]]
[[1 0 7]
 [2 5 0]
 [0 6 9]]


In [11]:
A_inv = np.linalg.inv(A) 
print(A_inv)

[[ 0.34883721 -0.13953488  0.09302326]
 [ 0.3255814   0.06976744 -0.04651163]
 [-0.27131783  0.10852713  0.03875969]]


In [14]:
A_invA = np.linalg.inv(A) * A
print (A_invA)

[[ 1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  0.00000000e+00  1.00000000e+00]]


Note: 输出其实就是单位阵 由于求逆矩阵的过程有四舍五入, 所以有点误差